### ISSUE TITLE
Support for _CPS1 directory

### ISSUE THREAD

**Issue by retrocaster** [RetroDriven/MiSTerMAME#10]
Jotego has suggested the following file structure for his CPS1 work:

_CPS1   (for MRA files)
_CPS1/mame   (for mame zips)
_CPS1/cores   (for rbf files)

It would be great if there was a configuration option that followed this structure for CPS1 related stuff. Or possibly it could autodetect that structure and behave accordingly.

**Comment by RetroDriven** [comment]
This should be all set when you run the Script again. Can you please test and confirm when you get a chance?

**Comment by retrocaster** [comment]
I had an existing structure as shown above but removed the .zip files from __CPS1/mame and then ran your latest script. This is what I have now:

_CPS (with mras)
_CPS/cores (with .rbf)
_CPS/mame (empty)

_CPS1 (no mras; only subdirs)
_CPS1/cores (empty)
_CPS1/mame (zip files)

**Comment by RetroDriven** [comment]
That's very strange. Try deleting the _CPS and _CPS1 Folders.

Run my Cache Remover Script. Run the Updater Script after and everything should be in as expected.

**Comment by retrocaster** [comment]
Yep, after following your steps things seem to be working as expected. Thanks for implementing this request!

**Comment by RetroDriven** [comment]
Excellent! You're welcome
