### ISSUE TITLE
Rygar unofficial core is re-downloaded every time

### ISSUE THREAD

**Issue by thepulserifle** [RetroDriven/MiSTerMAME#11]
Each time I run the Retrodriven updater, when going through the unofficial cores, the Rygar core is always re-downloaded despite not having an update in several months.

**Comment by RetroDriven** [comment]
Try either removing the Rygar core or renaming it from rygar to Rygar. After run the Script a couple times and see if the issue remains.

The script doesn't seem to like it being lower case for some reason. I'll figure a permanent fix for this.

**Comment by thepulserifle** [comment]
Confirmed - definitely a case issue. Attempted a rename and FileZilla
wasn’t having it, so I deleted. Ran the script twice. All good now.

**Comment by RetroDriven** [comment]
Perfect thanks for testing this out. Hopefully this will become an Official Core soon and this issue will go away for good.
