### ISSUE TITLE
Dig Dug II .mra is missing

### ISSUE THREAD

**Issue by PhantombrainM** [RetroDriven/MiSTerMAME#12]
Dig Dug II.mra is missing

**Comment by PhantombrainM** [comment]
Maybe I should add some info.
It used to be in _arcade folder. I deleted it by accident. 
And only _arcade/alternatives/dig dug ii (old) is still there.

Cant find the original in the repo anymore.

**Comment by RetroDriven** [comment]
Are you using the Official Updater to download those MRA files?

If so it should bring pulling that MRA file along with The Tower of Druaga Core.

**Comment by PhantombrainM** [comment]
Yes. I'm using v2.4

Interestingly I now renamed digdug2.zip, tower zip and tower mra and it's just downloading the mame zips. Tower mra also stays renamed only and is not downloading again.

Can you check by renaming one of your *.MRA's in _arcade folder?

**Comment by RetroDriven** [comment]
I meant the Official MiSTer Updater. Once Cores become Official I remove the MRA/RBF support on my end and just keep the MAME Zips. That way it avoids duplicates and issues.

**Comment by PhantombrainM** [comment]
Yes, I also ran that. And checked official MISTer git before opening this ticket here. It's not in the official git.

**Comment by RetroDriven** [comment]
It should be pulling it from the Official GitHub here.

https://github.com/MiSTer-devel/Arcade-Druaga_MiSTer/tree/master/releases

**Comment by PhantombrainM** [comment]
It doesn't. Try renaming a .mra.

But I haven't looked in the druaga folder but in digdug instead. So I overlooked that file.
Thank you for pointing out. However it's not pulling that file when you delete or rename it for me.

**Comment by RetroDriven** [comment]
Just to be clear you are using the update.sh script found here right? 

https://github.com/MiSTer-devel/Updater_script_MiSTer

I just tested this without creating an update.ini file for tweaking what the Official Updater downloads and it will pull in every Official MRA file including DigDug2.

**Comment by PhantombrainM** [comment]
Sorry, it wen't late in my timezone.

Yes. That's the script I ran too. Problem still remains. Deleting an *.mra or renaming it to *_.mra does not download it again. No .ini file here. I will investigate further.

But you can close this ticket here then. It seem's on my side. I thought there is a missing file here in Retrodriven or a problem in the script which is obviously not the case. Thank you for your support and the RD service! Take care!

**Comment by RetroDriven** [comment]
Sadly this seems to be more of an issue with the MiSTer Updater. I can still help out if needed though. DM me on Twitter if you have an account there.

You're welcome! I'm always here to help out and try to make things as easy as possible.
