### ISSUE TITLE
240p output enhancement. 

### ISSUE THREAD

**Issue by senkunmusashi** [RetroDriven/MiSTerMAME#13]
Thanks for this fantastic script! Would it be possible to add 15Khz video support like the official update script?  Flying blind when connected to CRT and need to switch to HDMI everytime for updating.

**Comment by RetroDriven** [comment]
You're welcome! I didn't realize this was an issue with running Scripts via 15khz and that the Official Updater has a way around it. Is there anything special on your end that you need to do via the INI file to make this work for the Official Updater?

**Comment by senkunmusashi** [comment]
Sorry for the late late reply. No, didn't have to do anything special in the ini, just via menu, scripts, update. First time it happened I forgot output was direct video to crt and I was expecting the crt screen to blank. Surprised it didn't. So then when to update retrodriven, and that's when the screen blanked. So came here to make a request.

**Comment by RetroDriven** [comment]
What happens if you set the following within your Mister.ini file?

`fb_terminal=0`
