### ISSUE TITLE
timeout while downloading cps1

### ISSUE THREAD

**Issue by sethenstien** [RetroDriven/MiSTerMAME#14]
The cps1 download keeps failing for me due to timeout. Is there anyway that the timeout can be turned off? Its downloading fine, its just the internet i'm using is a slower dsl connection.

**Comment by RetroDriven** [comment]
I have just removed the time out portion. Can you test this and let me know what happens please?

**Comment by sethenstien** [comment]
mhmm. works fine now. i guess the default length until the timeout just wasn't long enough for my internet. kept stopping at about 60%

**Comment by RetroDriven** [comment]
Excellent! It's probably best to do away with the time out in general with the CPS1 Mame Files getting larger now.
