### ISSUE TITLE
CPS1 returning to menu

### ISSUE THREAD

**Issue by sk8er000** [RetroDriven/MiSTerMAME#15]
Once I select a CPS1 game, when I press enter the mister goes back to the main screen of the menu

**Comment by RetroDriven** [comment]
Are you a Joetgo Patreon and have the CPS1 Core?

This is still in Beta and if you are not a Patreon with the Core it will not work.

**Comment by sk8er000** [comment]
I didn't know that, I'm sorry.
Thank you
