### ISSUE TITLE
Double dragon 2lim-0.ic55 file not found

### ISSUE THREAD

**Issue by sk8er000** [RetroDriven/MiSTerMAME#16]
If I try to load Double dragon I got the error " 2lim-0.ic55 file not found" and then black screen. I can access to the core menu but the game doesn't start.

**Comment by RetroDriven** [comment]
I just loaded up Double Dragon without issue on my end. 

Do you have the ddragon.zip file inside of your Mame folder?

_Arcade/Mame/ddragon.zip

**Comment by sk8er000** [comment]
Yes, I've the zip downloaded from the script

**Comment by sk8er000** [comment]
I've deleted the ddragon.zip file from_Arcade/Mame/ddragon.zip and run the script again and it downloaded the rom again, now it's working. Maybe it was somehow corrupted the first time
