### ISSUE TITLE
MAME set is out sync wrt Mister MRA

### ISSUE THREAD

**Issue by piso77** [RetroDriven/MiSTerMAME#19]
Just did a fresh install, and it turns out the MAME roms are out of sync wrt Mister mra: all roms are missing this or that rom dump file, and none work anymore (tried anteater, arkanoid, xevious, etcetc).

Could you check what is going on?

**Comment by makenai** [comment]
@piso77 Have you tried running the main MiSTer update script once again? I was having a similar problem and that resolved the issue for me.

**Comment by piso77** [comment]
Ok, i did a couple of updates and though nothing else changed, now it works - super weird.

Anyhow, closing here.
