### ISSUE TITLE
none of the cores is working. 

### ISSUE THREAD

**Issue by Dud3z** [RetroDriven/MiSTerMAME#21]
seems like the mra files are not recgnized.

**Comment by RetroDriven** [comment]
Please run the Script again to Migrate over to the new SE Script. After that please run the SE Script that will be within your Scripts folder automatically. Let me know if that does or doesn't clear up this issue.

**Comment by Dud3z** [comment]
it did not... =(
all arcade cores i try to start are telling me that a file is missing or not found. the jotego cps1 core is starting but is black. if i press start some kind of credits are opening. how do i reset without reinstalling the whole mister?

**Comment by deftones327** [comment]
make sure you have no empty mame folders elsewhere

**Comment by Dud3z** [comment]
i deleted the _Arcade folder... started the update (mister) again and after that startet the retrodriven script again... still the same problem

**Comment by deftones327** [comment]
I meant none at root or under Games

**Comment by Dud3z** [comment]
where should i look?

**Comment by chrisesharp** [comment]
I just did a fresh install of MiSTer, installed the SE script, ran it (it appeared to be copying everything over) and get exactly the same problem - various files missing for each core.

**Comment by Spiritof** [comment]
> 
> 
> I meant none at root or under Games

This.

Check to see if there isn't an empty "mame" folder inside "games". Delete it. 

It fixed the problem for me. Loaded several cores with no problems, the only funny one I've noticed was that Jotego's GnG displayed upside down. :)

**Comment by Dud3z** [comment]
yeah i just looked at the folders and had a empty mame folder... it worked for me too
