### ISSUE TITLE
'_Alternatives' - option to not download these files

### ISSUE THREAD

**Issue by neosquid** [RetroDriven/MiSTerMAME#23]
Could an option be added to the 'Update_RetroDriven_MAME_SE.ini' to not download Alternative files, e.g DOWNLOAD_MRA_ALTERNATIVES="false" ?

Thanks!

**Comment by RetroDriven** [comment]
I should be able to make that happen. I'll do some testing.

**Comment by damanloox** [comment]
Please do! there's enough stuff to play with - I'm sure quite a few people would prefer not to download )alternatives at all..

**Comment by RetroDriven** [comment]
I will get this tested out and added this weekend!

**Comment by RetroDriven** [comment]
This should be all set now with the new v1.3 Release.

The following by default has been added within the Script/INI File. Set that to False if you don't want to download the Alternative MRA Files.

`DOWNLOAD_MRA_ALTERNATIVES="True"
`

Please test this out when possible and let me know if everything is good.
