### ISSUE TITLE
enhancement: option to unpack mra to original location

### ISSUE THREAD

**Issue by olli4711** [RetroDriven/MiSTerMAME#5]
Hi, would be great to have an option to unpack new MRAs and Alternatives to original location. e.g. _Arcade instead of _Aracde/Unofficial

**Comment by RetroDriven** [comment]
Hi - I can add an option for that for the INI file to see. I defaulted them to the Unofficial folder to avoid issues with the Official MRA files when Cores get moved over to the Official MiSTer. 

I'll have to test this but I would assume the Unofficial MRA files would get overwritten when the Official Updater checks/finds/downloads.

**Comment by RetroDriven** [comment]
This should be working as expected now. You will just need to change the INI option from `MRA_UNOFFICIAL_SUBFOLDER="True"` to `MRA_UNOFFICIAL_SUBFOLDER="False"`

Please test this out and let me know if you have any questions or issues.

**Comment by olli4711** [comment]
Thanks! I dont have an _Unofficial folder any longer, but still _Jotego and _Sega System 1 folder are created. Any chance to unzip them to _Arcade directly?

**Comment by RetroDriven** [comment]
You're welcome. I didn't realize you wanted the Jotego and Sega System 1 stuff in the root Arcade folder. I just added this in for you. Since Jotego has some duplicate cores as MiSTer Official(1942, 1943, GNG) I had the Script rename those to CoreName_Jotega.mra to avoid issues.

Give this a test when you can and let me know how it works for you please.

**Comment by olli4711** [comment]
Looks good in a first test run. Thanks!
Will do some more testing on Wednesday and give feedback.

**Comment by RetroDriven** [comment]
You're welcome. That sounds good to me. If there are any issues just let me know and I'll get them worked out.

**Comment by olli4711** [comment]
Tested again with an empty _Arcade folder, ran official updater and your one afterwards.
Got a clean and working install :-) Thanks again

**Comment by RetroDriven** [comment]
Excellent! No problem at all. If you have any issues or ideas for improvements down the road just let me know.
