### ISSUE TITLE
Thanks for the script.

### ISSUE THREAD

**Issue by TheRealYasri** [RetroDriven/MiSTerMAME#7]
Just want to say thanks for making this script. You took something that normally is a pain the butt, and made it a run and done. If you want keep this open for other to say thanks, not enough of that on the internet some times.

**Comment by RetroDriven** [comment]
You're welcome! I appreaciate this post so thank you as well =)

This was something that I wanted to create for myself as a way to learn and keep my MAME files small, organized, and easily updated without having to downoad the entire MAME set. 

It turned into a labor of love and something I wanted to share this with others looking for the same common goal. Automating and scripting is something that is fun and rewarding so it's my pleasure to keep giving back in any way I can to this awesome MiSTer Community.

**Comment by RetroDriven** [comment]
FYI - I am working on some other Scripts that I think will be helpful as well. As of now these will be Patreon Subscriber only Scripts. I'm not sure if I will release those here on GitHub and the Public down the road yet or not(I'm leaning towards not). I just thought I would throw this out there in case you or anyone else reading this might be interested in that.

**Comment by djvelocitee** [comment]
Yes! Thank you for all you do! Made this whole Arcade setup/play nice and simple. The BEST!

**Comment by RetroDriven** [comment]
You're welcome - That is goal and I'm just happy to help make that come true.
