### ISSUE TITLE
More MRA files to include.

### ISSUE THREAD

**Issue by TheRealYasri** [RetroDriven/MiSTerMAME#9]
Might want to add alternatives mra files for jotego's cores.

https://github.com/jotego/jtbin/tree/master/mister/mra/_alternatives

I also posted to a closed ticket if it does not notify you.
https://github.com/RetroDriven/MiSTerMAME/issues/6#issuecomment-590002646

**Comment by TheRealYasri** [comment]
Changed the name to a more generic name, so others can add any they find here.

Final Fight Anniversary Edition 
https://github.com/originalgrego/FinalFightAE-Installer/blob/master/ffightae.mra

You need to patch ffight.zip and the file you end up with is ffightae.zip.

**Comment by RetroDriven** [comment]
Good ideas here thanks!

Everything should be there now as expected. Please test and confirm when you get a chance.

**Comment by TheRealYasri** [comment]
Test about a dozen games added for a few mins each and they seem to work.

**Comment by RetroDriven** [comment]
Perfect thanks. If you come across any that don't work just let me know.
